# Generated by Django 4.2.7 on 2023-11-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
